#!/bin/bash

make

for ((i=0 ; i<=13; i++))
  do
    if [[ $i -eq 0 ]];
    then
        echo "-------------------------------------------"
        echo "Prueba por defecto"
    fi

    if [[ $i -eq 1 ]];
    then
        echo "-------------------------------------------"
        echo "Pruebas para RR.c"
    fi

    if [[ $i -eq 5 ]];
    then
        echo "-------------------------------------------"
        echo "Pruebas para RRS.c"
    fi

    if [[ $i -eq 10 ]];
    then
        echo "-------------------------------------------"
        echo "Pruebas para RRS.c"
    fi

    echo "------------------------"
    echo "Test $i"
    echo "------------------------"
    echo ""
    ./main test$i
    echo ""
  done